### ISSUE TITLE
1.0.16b2 - Failed to extract data for MyDolphinPlusSensorEntityDescription

### ISSUE THREAD

**Issue by AnthonyBe** [sh00t2kill/dolphin-robot#216] opened 2024-07-06 13:01 UTC
This seems to have started with HA 2024.7 and integration 1.0.16b0
Have also tried 1.0.16b2 but no change.
```
Logger: custom_components.mydolphin_plus.managers.coordinator
Source: custom_components/mydolphin_plus/managers/coordinator.py:399
integration: MyDolphin Plus (documentation, issues)
First occurred: 22:47:40 (130 occurrences)
Last logged: 22:58:35

Failed to extract data for MyDolphinPlusSensorEntityDescription(key='cycle_time_left', device_class=<SensorDeviceClass.DURATION: 'duration'>, entity_category=None, entity_registry_enabled_default=True, entity_registry_visible_default=True, force_update=False, icon=None, has_entity_name=False, name='Cycle Time Left', translation_key='cycle_time_left', translation_placeholders=None, unit_of_measurement=None, platform=<Platform.SENSOR: 'sensor'>, supported_robot=<RobotFamily.ALL: 'all'>, last_reset=None, native_unit_of_measurement=<UnitOfTime.SECONDS: 's'>, options=None, state_class=<SensorStateClass.MEASUREMENT: 'measurement'>, suggested_display_precision=None, suggested_unit_of_measurement=None), Error: list index out of range, Line: 393
```

Diagnostic download:
[config_entry-mydolphin_plus-f51e3ee42c0fc67259d37e0f24eff881-1.json](https://github.com/user-attachments/files/16116199/config_entry-mydolphin_plus-f51e3ee42c0fc67259d37e0f24eff881-1.json)

**Comment by elad-bar** [comment] 2024-07-06 13:42
Please provide debug level logs

Thanks

**Comment by AnthonyBe** [comment] 2024-07-07 04:44
hmm... I can't seem to get it to repro again today.
I'll keep at it but if I have no joy in the next day or two I'll close this out and assume it was just one of 'those' random spurious events.

**Comment by jasoncodes** [comment] 2024-07-07 05:13
I also had the same error yesterday as soon as I installed 1.0.16b2. It stopped this morning at 10:00+10:00 (00:00 UTC) exactly when a scheduled clean started and hasn’t reoccured during cleaning or cleaning finished. I restarted Home Assistant just now and it hasn’t triggered the error. Will post an update here if I see it again.

**Comment by elad-bar** [comment] 2024-07-07 05:35
release [v1.0.16b3](https://github.com/sh00t2kill/dolphin-robot/releases/tag/v1.0.16b3),
pls check
thanks

**Comment by AnthonyBe** [comment] 2024-07-07 09:53
Installed release [v1.0.16b3](https://github.com/sh00t2kill/dolphin-robot/releases/tag/v1.0.16b3) and am getting the error again. 
Interesting observation from @jasoncodes that it stopped for him after a scheduled clean ran. I've restarted HA a few times and am getting the error constantly. Woo be interesting to see if it goes away when my cleaner's schedule job runs overnight.

**Comment by elad-bar** [comment] 2024-07-07 10:01
If still happens in b3, i will need debug level logs to understand the root cause

**Comment by AnthonyBe** [comment] 2024-07-07 10:21
[home-assistant_2024-07-07T10-18-56.069Z.log.txt](https://github.com/user-attachments/files/16118826/home-assistant_2024-07-07T10-18-56.069Z.log.txt)
Debug level log attached. 
I'm running HA 2024.7.1 and integration release v1.0.16b3

**Comment by jasoncodes** [comment] 2024-07-07 11:03
Installed v1.0.16b3 and the problem started again. “Cycle Time Left” is showing in the UI as “Unknown”. Manually started a clean via the iPhone app and as soon as the state changed to “Cleaning”, the “Cycle Time Left” started counting down, and the error message stopped being logged. When I stopped the cleaning (state back to “Idle (Weekly)”), the problem returned.

History suggests that at the end of a full clean cycle the value stays at zero instead of going back to “Unknown”, which is presumably why I saw the problem stop earlier today. No debug from me right now but I can prepare one later on if the existing one in this Issue isn’t enough.

**Comment by elad-bar** [comment] 2024-07-08 06:25
it was bit different error but with the same result of not working,
i fixed the state within [v1.0.16b4](https://github.com/sh00t2kill/dolphin-robot/releases/tag/v1.0.16b4),
please check and update

thanks

**Comment by jasoncodes** [comment] 2024-07-08 06:46
I’ve just installed v1.0.16b4 and it’s looking good. Cycle Time Left is initially zero and correctly starts counting down when I start cleaning. When cleaning is stopped it returns to zero. No warnings/errors in the logs. Thanks!

**Comment by elad-bar** [comment] 2024-07-08 06:49
Great, will create PR for official release

**Comment by elad-bar** [comment] 2024-07-08 07:35
Released [v1.0.16](https://github.com/sh00t2kill/dolphin-robot/releases/tag/v1.0.16), pls let me know if we can close this issue 

thanks

**Comment by AnthonyBe** [comment] 2024-07-08 08:06
I updated to [v1.0.16](https://github.com/sh00t2kill/dolphin-robot/releases/tag/v1.0.16)
Looks good. No errors observed.

**Comment by sh00t2kill** [comment] 2024-07-08 08:13
Thanks @elad-bar

**Closed by sh00t2kill** 2024-07-08 08:13 UTC
