### ISSUE TITLE
Can't add integration in Home Assistant, ERROR

### ISSUE THREAD

**Issue by ahuffman** [sh00t2kill/dolphin-robot#145] opened 2023-07-28 02:13 UTC
I have v1.0.2 of the integration installed via HACS, first time ever attempting to install it.  I restarted Home Assistant and when I attempt to add the new integration from Home Assistant setting, I receive the error message: `Config flow could not be loaded: {"message":"Invalid handler specified"}`

In the container logs I find the following:

```
2023-07-27 21:54:59.076 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration mydolphin_plus: Exception importing custom_components.mydolphin_plus.config_flow
```

My Home Assistant is version is:
```
Home Assistant 2023.5.4
Frontend 20230503.3 - latest
```

**Comment by sh00t2kill** [comment] 2023-07-28 03:22
Hi @ahuffman 

I was having some strange errors too earlier today but they have since dissapeared.

Can you try it again ? I think the maytronics platform was failing logins.

**Comment by elad-bar** [comment] 2023-07-28 04:31
Please try to install v1.0.1 and see if it work, I will check it in few days, 
@sh00t2kill according to the logs, it's not loading the integration creation ui because of reference loading exception.

Thanks

**Comment by ahuffman** [comment] 2023-07-28 13:56
I tried v1.0.1 as well yesterday and again this morning.  Same error message.

**Comment by elad-bar** [comment] 2023-07-29 14:55
not sure what happened, over the last week I work on new implementation (adopt it from another integration I wrote) so i will not try to reproduce it with older version, 
after reviewing the PR for next version, I will post here that you can test it and see if it solved the problem

**Comment by SethL** [comment] 2023-08-08 23:08
I'm having this same issue as well. 
" Config flow could not be loaded: {"message":"Invalid handler specified"} "

**Comment by elad-bar** [comment] 2023-08-09 03:44
Can you please share debug log level?

Thanks

**Comment by elad-bar** [comment] 2023-08-09 05:29
which version of integration and HA are you using?

**Comment by ahuffman** [comment] 2023-08-10 17:37
@elad-bar, quick update here from my end.  I'm on 1.0.3, still having the same issue on the homeassistant/home-assistant:stable docker tag.  However, I just tested with the homeassistant/home-assistant:latest docker tag and I was able to get setup fine.

**Comment by elad-bar** [comment] 2023-08-11 06:24
docker image repo changed to `ghcr.io/home-assistant/home-assistant:stable`, 
@ahuffman, just to understand with latest - are you on the latest HA (2023.8.1) + latest integration (1.0.3) and problem gone or exists?

@SethL same question to you?

thanks

**Comment by ahuffman** [comment] 2023-08-11 15:12
I changed from stable tag to latest tag.

Version where I've verified the integration v1.0.3 to work is HA 2023.8.1.

**Comment by SethL** [comment] 2023-08-11 15:17
I'm on HA 2022.11.2 (every time I upgrade there is always something that I have to fix so I usually avoid upgrades) and v 1.0.3 of the integration.
If the fix is to upgrade I can do that.  I'm just gun shy :-)

**Comment by elad-bar** [comment] 2023-08-11 15:21
@SethL seems that your issue is related to lack of compatability to libraries (and maybe even python) required to interact with HA,
Although it is painful process, strongly suggest to do that once and then update after first hotfix,
I'm updating automatically the moment it is released, and usually nothing happens, you can also check the RC release notes few days before HA gets released (for breaking changes)

@ahuffman with latest it work, stable not, right?

**Comment by elad-bar** [comment] 2024-01-07 04:42
Is this issue still relevant or can we close it?

Thanks

**Closed** 2024-01-08 17:15 UTC
